### ISSUE TITLE
How can I get 6 (lan, lot) coordinates of a hexagon of a cell grid?

### ISSUE THREAD

**Issue by alexkokorin2** [GIScience/geogrid#2]
I didn't find such a method in both _CellGrid_ & _ISEA3H_ classes, I believe there should be an opportunity to do this (e.g., for drawing/visualizing hexagons).

**Comment by mocnik-science** [comment]
Hi!
There is actually a library called [geogrid.js](http://www.github.com/giscience/geogrid.js) that seems to do what you want.  The geogrid library computes the centres of the grid cells and (you are right) not the coordinates of the six points defining the boundary.  However, the library geogrid.js can be used in the browser to estimate the coordinates of these six points and to visualize the result information.  If this should not solve your problem, feel welcome to explain your use case in more detail (maybe via e-mail).
Best regards
