### ISSUE TITLE
Leverage the structure of projection to get distance between two GridCells

### ISSUE THREAD

**Issue by gunjanthesystem** [GIScience/geogrid#3]
Thanks for this implementation. Is there a way to get the distance between two grid cells without actually computing the distance (e.g., haversine, computationally a bit expensive) between their centre's lat lon ?  I guess the cells are fairly regular (except perhaps the 12 pentagons) and equal area, hence couldn't the network of cells themselves serve as a measure of distance (instead of going through lat,lon). I apologise if the functionality is already there and i missed to notice it. Thanks again.

**Comment by mocnik-science** [comment]
The distance between cells on the icosahedron is actually very simple to determine. However, the projection from the icosahedron the the sphere is, as you say, equal area and not equal distant.  This is why you would have to find a formula describing how distances transform under the projection.  I assume that this will be much more work than just using the Haversine formula.
