### ISSUE TITLE
Any proposed method to get parent child and heighbours

### ISSUE THREAD

**Issue by am2222** [GIScience/geogrid#5]
Hi,
Is it possible to get the parent of an hexagon cell from index value?lets say we have an id + 24 43125632 124326532 is there any way to get its parent hexagon?lets say in resolution 1?

also I was wondering to find a way to get neighbors around this hexagon. I was thinking of guessing them by distance of cell centers in that resolution but I have no idea if it works

**Comment by mocnik-science** [comment]
Hi!
As you might know, hexagon cells can have more than one parent.
About the neighbours: You can easily guess them by distance. That is, at least, what I do.
I hope that this helps.

**Comment by am2222** [comment]
@mocnik-science Hi,
Yes exactly I was planing to find them by distance, I was wondering to find them from any other ways than regular distance calculations.

**Comment by mocnik-science** [comment]
Regular distance calculation seems to be the quickest way of finding neighbours.

**Comment by am2222** [comment]
@mcauer Thanks so much, Is there any sample code to figure out how you have dealt with 360degree direction around a central cell?

**Comment by mocnik-science** [comment]
No, there is not.

**Comment by am2222** [comment]
@mocnik-science Thanks so much
