### ISSUE TITLE
Unit test ISEA3Test.numberOfCellsByGrid fails

### ISSUE THREAD

**Issue by jcb9000** [GIScience/geogrid#6]
The numberofCellsByGrid test contains a loop testing resolutions [1,12]. The test fails on resolution values: 3, 4, 7, 8, and 9. 

The values of 'cells' and 'cellsExpected' are always different by 4. 

Example: at resolution 3, cells = 276, cellsExpected = 272.  At resolution 9, cells = 196836, cellsExpected = 196832.

**Comment by mocnik-science** [comment]
Thanks for opening the ticket. Something in Java seems to have been adapted because the tests were fine in before. I have adapted the code now. The issue should be resolved now.
